-- RIHULA ADMIN ACTIVITY AUDIT
-- Run in order: Part 1, Part 2, Part 3, Part 4.

-- ================= PART 1 =================
CREATE TABLE IF NOT EXISTS public.activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_auth_id UUID,
  admin_name TEXT DEFAULT 'Admin',
  admin_email TEXT,
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS admin_auth_id UUID;
ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS admin_name TEXT;
ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS admin_email TEXT;
ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS action TEXT;
ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS entity_type TEXT;
ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS entity_id TEXT;
ALTER TABLE public.activity_logs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins read activity logs" ON public.activity_logs;
CREATE POLICY "Admins read activity logs" ON public.activity_logs
FOR SELECT TO authenticated USING (public.is_rihula_admin());

CREATE INDEX IF NOT EXISTS activity_logs_created_at_idx ON public.activity_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS activity_logs_admin_auth_id_idx ON public.activity_logs(admin_auth_id);

-- ================= PART 2 =================
CREATE OR REPLACE FUNCTION public.log_admin_activity(p_action TEXT)
RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  u UUID := auth.uid();
  n TEXT; e TEXT; r BIGINT;
BEGIN
  SELECT name,email INTO n,e FROM public.members
  WHERE auth_id=u AND is_admin=true
    AND LOWER(COALESCE(status,'active')) NOT IN ('blocked','suspended','inactive')
  LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'Only an active RIHULA admin can create activity records.'; END IF;
  INSERT INTO public.activity_logs(admin_auth_id,admin_name,admin_email,action)
  VALUES(u,COALESCE(NULLIF(TRIM(n),''),'Admin'),NULLIF(TRIM(e),''),LEFT(COALESCE(NULLIF(TRIM(p_action),''),'Admin activity'),500))
  RETURNING id INTO r;
  RETURN r;
END;
$$;
REVOKE ALL ON FUNCTION public.log_admin_activity(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_admin_activity(TEXT) TO authenticated;

-- ================= PART 3 =================
-- Audit only meaningful administrator actions.
-- Page visits, dashboard views, normal member edits, login/logout and reads are NOT logged.
CREATE OR REPLACE FUNCTION public.rihula_audit_admin_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  u UUID := auth.uid();
  n TEXT; e TEXT; a TEXT; eid TEXT;
  phone TEXT; mname TEXT; amount TEXT; title TEXT;
  old_status TEXT; new_status TEXT; body TEXT;
BEGIN
  IF u IS NULL OR TG_TABLE_NAME='activity_logs' THEN
    RETURN COALESCE(NEW,OLD);
  END IF;

  -- Only an active RIHULA admin can create audit records.
  SELECT name,email INTO n,e FROM public.members
  WHERE auth_id=u AND is_admin=true
    AND LOWER(COALESCE(status,'active')) NOT IN ('blocked','suspended','inactive')
  LIMIT 1;
  IF NOT FOUND THEN
    RETURN COALESCE(NEW,OLD);
  END IF;

  eid:=COALESCE(TO_JSONB(NEW)->>'id',TO_JSONB(OLD)->>'id',TO_JSONB(NEW)->>'phone',TO_JSONB(OLD)->>'phone','');

  -- MEMBER WORKFLOW: add, approve, reject and delete only.
  IF TG_TABLE_NAME='members' THEN
    phone:=COALESCE(TO_JSONB(NEW)->>'phone',TO_JSONB(OLD)->>'phone','');
    mname:=COALESCE(TO_JSONB(NEW)->>'name',TO_JSONB(OLD)->>'name','Member');
    old_status:=COALESCE(TO_JSONB(OLD)->>'status','');
    new_status:=COALESCE(TO_JSONB(NEW)->>'status','');

    IF TG_OP='INSERT' THEN
      a:='Added member: '||mname||CASE WHEN phone<>'' THEN ' ('||phone||')' ELSE '' END;
    ELSIF TG_OP='DELETE' THEN
      a:='Deleted member: '||mname||CASE WHEN phone<>'' THEN ' ('||phone||')' ELSE '' END;
    ELSIF TG_OP='UPDATE' AND LOWER(new_status)='approved' AND LOWER(old_status) IS DISTINCT FROM 'approved' THEN
      a:='Approved member: '||mname||CASE WHEN phone<>'' THEN ' ('||phone||')' ELSE '' END;
    ELSIF TG_OP='UPDATE' AND LOWER(new_status)='rejected' AND LOWER(old_status) IS DISTINCT FROM 'rejected' THEN
      a:='Rejected member: '||mname||CASE WHEN phone<>'' THEN ' ('||phone||')' ELSE '' END;
    ELSE
      -- Normal member profile edits are intentionally ignored.
      RETURN COALESCE(NEW,OLD);
    END IF;

  -- CONTRIBUTIONS: record any actual admin change to a contribution.
  ELSIF TG_TABLE_NAME='contributions' THEN
    phone:=COALESCE(TO_JSONB(NEW)->>'member_phone',TO_JSONB(OLD)->>'member_phone',TO_JSONB(NEW)->>'phone',TO_JSONB(OLD)->>'phone','');
    amount:=COALESCE(TO_JSONB(NEW)->>'amount',TO_JSONB(OLD)->>'amount','0');
    a:=CASE TG_OP
      WHEN 'INSERT' THEN 'Recorded contribution: KSh '||amount||CASE WHEN phone<>'' THEN ' for '||phone ELSE '' END
      WHEN 'UPDATE' THEN 'Edited contribution: KSh '||amount||CASE WHEN phone<>'' THEN ' for '||phone ELSE '' END
      WHEN 'DELETE' THEN 'Deleted contribution: KSh '||amount||CASE WHEN phone<>'' THEN ' for '||phone ELSE '' END
    END;

  -- WITHDRAWALS: record any actual admin change to a withdrawal.
  ELSIF TG_TABLE_NAME='withdrawals' THEN
    phone:=COALESCE(TO_JSONB(NEW)->>'member_phone',TO_JSONB(OLD)->>'member_phone',TO_JSONB(NEW)->>'phone',TO_JSONB(OLD)->>'phone','');
    amount:=COALESCE(TO_JSONB(NEW)->>'amount',TO_JSONB(OLD)->>'amount','0');
    a:=CASE TG_OP
      WHEN 'INSERT' THEN 'Recorded withdrawal: KSh '||amount||CASE WHEN phone<>'' THEN ' for '||phone ELSE '' END
      WHEN 'UPDATE' THEN 'Edited withdrawal: KSh '||amount||CASE WHEN phone<>'' THEN ' for '||phone ELSE '' END
      WHEN 'DELETE' THEN 'Deleted withdrawal: KSh '||amount||CASE WHEN phone<>'' THEN ' for '||phone ELSE '' END
    END;

  -- GALLERY.
  ELSIF TG_TABLE_NAME='gallery_images' THEN
    title:=COALESCE(TO_JSONB(NEW)->>'title',TO_JSONB(OLD)->>'title',TO_JSONB(NEW)->>'name',TO_JSONB(OLD)->>'name','Gallery photo');
    a:=CASE TG_OP
      WHEN 'INSERT' THEN 'Uploaded gallery photo: '||title
      WHEN 'UPDATE' THEN 'Updated gallery photo: '||title
      WHEN 'DELETE' THEN 'Deleted gallery photo: '||title
    END;

  -- ANNOUNCEMENTS.
  ELSIF TG_TABLE_NAME='announcements' THEN
    title:=COALESCE(TO_JSONB(NEW)->>'title',TO_JSONB(OLD)->>'title','Announcement');
    a:=CASE TG_OP
      WHEN 'INSERT' THEN 'Posted announcement: '||title
      WHEN 'UPDATE' THEN 'Edited announcement: '||title
      WHEN 'DELETE' THEN 'Deleted announcement: '||title
    END;

  -- MEMBER NOTIFICATIONS.
  ELSIF TG_TABLE_NAME='notifications' THEN
    title:=COALESCE(TO_JSONB(NEW)->>'title',TO_JSONB(OLD)->>'title','Notification');
    body:=COALESCE(TO_JSONB(NEW)->>'message',TO_JSONB(OLD)->>'message','');
    a:=CASE TG_OP
      WHEN 'INSERT' THEN 'Sent notification: '||title
      WHEN 'UPDATE' THEN 'Edited notification: '||title
      WHEN 'DELETE' THEN 'Deleted notification: '||title
    END;

  -- OTHER IMPORTANT ADMIN CONTENT CHANGES.
  ELSIF TG_TABLE_NAME='leadership' THEN
    title:=COALESCE(TO_JSONB(NEW)->>'position',TO_JSONB(OLD)->>'position','Leadership');
    a:=CASE TG_OP
      WHEN 'INSERT' THEN 'Added leadership record: '||title
      WHEN 'UPDATE' THEN 'Updated leadership record: '||title
      WHEN 'DELETE' THEN 'Deleted leadership record: '||title
    END;
  ELSE
    -- Absolutely no generic "INSERT/UPDATE/DELETE on table" records.
    RETURN COALESCE(NEW,OLD);
  END IF;

  INSERT INTO public.activity_logs(admin_auth_id,admin_name,admin_email,action,entity_type,entity_id)
  VALUES(
    u,
    COALESCE(NULLIF(TRIM(n),''),'Admin'),
    NULLIF(TRIM(e),''),
    LEFT(COALESCE(a,'Admin activity'),500),
    TG_TABLE_NAME,
    NULLIF(eid,'')
  );

  RETURN COALESCE(NEW,OLD);
EXCEPTION WHEN OTHERS THEN
  -- Never block the underlying RIHULA action because audit logging failed.
  RETURN COALESCE(NEW,OLD);
END;
$$;

REVOKE ALL ON FUNCTION public.rihula_audit_admin_mutation() FROM PUBLIC;

-- ================= PART 4 =================
-- Remove the old audit trigger from every public table, then install it ONLY
-- on tables whose actions should appear in Admin Activities.
DO $$
DECLARE r RECORD; tbl TEXT;
BEGIN
  FOR r IN
    SELECT tablename
    FROM pg_tables
    WHERE schemaname='public'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS rihula_admin_audit ON public.%I',r.tablename);
  END LOOP;

  FOREACH tbl IN ARRAY ARRAY['members','contributions','withdrawals','announcements','notifications','gallery_images','leadership'] LOOP
    IF to_regclass('public.'||tbl) IS NOT NULL THEN
      EXECUTE format(
        'CREATE TRIGGER rihula_admin_audit AFTER INSERT OR UPDATE OR DELETE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.rihula_audit_admin_mutation()',
        tbl
      );
    END IF;
  END LOOP;
END $$;

-- ================= PART 5 =================
-- Remove old records that do not belong in the meaningful audit trail.
DELETE FROM public.activity_logs
WHERE action = 'Opened Admin Activities'
   OR action LIKE 'Edited member:%'
   OR action = 'Signed out of Admin Dashboard'
   OR action ILIKE '%Admin Dashboard%';

-- Keep the manual logging RPC restricted to the same meaningful actions.
CREATE OR REPLACE FUNCTION public.log_admin_activity(p_action TEXT)
RETURNS BIGINT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  cleaned TEXT := LEFT(TRIM(COALESCE(p_action,'')),500);
  allowed BOOLEAN := FALSE;
  u UUID := auth.uid();
  n TEXT; e TEXT; r BIGINT;
BEGIN
  -- This RPC is intentionally narrow. It cannot be used to log page visits,
  -- dashboard opens, normal member edits, login/logout, or arbitrary text.
  allowed := cleaned ~* '^(Added member:|Approved member:|Rejected member:|Deleted member:|Recorded contribution:|Edited contribution:|Deleted contribution:|Recorded withdrawal:|Edited withdrawal:|Deleted withdrawal:|Uploaded gallery photo:|Updated gallery photo:|Deleted gallery photo:|Posted announcement:|Edited announcement:|Deleted announcement:|Sent notification:|Edited notification:|Deleted notification:)';
  IF NOT allowed THEN RETURN NULL; END IF;

  SELECT name,email INTO n,e FROM public.members
  WHERE auth_id=u AND is_admin=true
    AND LOWER(COALESCE(status,'active')) NOT IN ('blocked','suspended','inactive')
  LIMIT 1;
  IF NOT FOUND THEN RAISE EXCEPTION 'Only an active RIHULA admin can create activity records.'; END IF;

  INSERT INTO public.activity_logs(admin_auth_id,admin_name,admin_email,action)
  VALUES(u,COALESCE(NULLIF(TRIM(n),''),'Admin'),NULLIF(TRIM(e),''),cleaned)
  RETURNING id INTO r;
  RETURN r;
END;
$$;
REVOKE ALL ON FUNCTION public.log_admin_activity(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.log_admin_activity(TEXT) TO authenticated;
