-- RIHULA ADMIN + WITHDRAWAL SECURITY HARDENING
-- Run in Supabase SQL Editor after confirming the members.role values used by your project.
--
-- IMPORTANT:
-- 1. Keep the publishable/anon key in the frontend; NEVER put a service_role key in JS.
-- 2. Create admin users through Supabase Authentication.
-- 3. Link the auth user to members.auth_id and set members.role to one of:
--    admin, administrator, chairperson, secretary, treasurer.
-- 4. Review existing policies before enabling these rules in a live database.

create or replace function public.is_rihula_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.members m
    where m.auth_id = auth.uid()
      and lower(coalesce(m.role, '')) in
          ('admin','administrator','chairperson','secretary','treasurer')
      and lower(coalesce(m.status, 'active')) not in
          ('blocked','suspended','inactive')
  );
$$;

revoke all on function public.is_rihula_admin() from public;
grant execute on function public.is_rihula_admin() to authenticated;

-- Withdrawal integrity
create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  member_phone text not null,
  amount numeric(12,2) not null check (amount > 0 and amount <= 10000000),
  reason text,
  created_at timestamptz not null default now(),
  created_by uuid default auth.uid()
);

alter table public.withdrawals enable row level security;

create index if not exists withdrawals_member_phone_idx
on public.withdrawals(member_phone);

-- Admins can manage withdrawals. Authenticated members may read only their own
-- withdrawals when the phone number matches their member record.
drop policy if exists "Admins manage withdrawals" on public.withdrawals;
create policy "Admins manage withdrawals"
on public.withdrawals
for all to authenticated
using (public.is_rihula_admin())
with check (public.is_rihula_admin());

drop policy if exists "Members read own withdrawals" on public.withdrawals;
create policy "Members read own withdrawals"
on public.withdrawals
for select to authenticated
using (
  exists (
    select 1 from public.members m
    where m.auth_id = auth.uid()
      and m.phone = withdrawals.member_phone
  )
);

-- Optional hardening for the most sensitive admin mutations.
-- These policies are intentionally scoped to admin roles.
alter table public.contributions enable row level security;

drop policy if exists "Admins manage contributions" on public.contributions;
create policy "Admins manage contributions"
on public.contributions
for all to authenticated
using (public.is_rihula_admin())
with check (public.is_rihula_admin());

alter table public.announcements enable row level security;

drop policy if exists "Admins manage announcements" on public.announcements;
create policy "Admins manage announcements"
on public.announcements
for all to authenticated
using (public.is_rihula_admin())
with check (public.is_rihula_admin());

-- NOTE:
-- Do not create broad "authenticated users can do everything" policies on
-- members, contributions, withdrawals, announcements, or settings.
-- If an existing policy grants UPDATE/DELETE/INSERT to every authenticated
-- user, remove or narrow that policy after testing the member flows.
