-- RIHULA Withdrawal Fix
-- Run this in Supabase SQL Editor if the withdrawals table does not already exist.
-- Adjust the member phone column name if your existing members table uses another name.

create table if not exists public.withdrawals (
  id bigint generated by default as identity primary key,
  member_phone text not null,
  amount numeric(12,2) not null check (amount > 0),
  reason text,
  created_at timestamptz not null default now()
);

create index if not exists withdrawals_member_phone_idx
  on public.withdrawals(member_phone);

-- If your existing contributions table does not have a usable phone column,
-- change member_phone in the JavaScript helper to the actual column.
-- The frontend helper tries member_phone and phone automatically.

-- IMPORTANT:
-- If Row Level Security is enabled, create policies appropriate to your app.
-- Do not blindly disable RLS in production.
